### ISSUE TITLE
cannot launch binder nor run notebooks locally

### ISSUE THREAD

**Issue by veroandreo** [petrasovaa/grass-gis-workshop-FOSS4G-2021#3]
I have tried to launch binder already 3 times, waited for the whole compilation to finish (there are no errors reported), but Binder does not launch jupyter lab... any ideas what can be wrong?

Also, I'm trying to run the notebooks locally, changing `gisbase` in the first notebook to my compiled version of grass8, but I get "Module not found" for `grass.jupyter`. I recompiled main branch earlier today, so it's fresh and `grass.scripts` seems to be imported without errors. 

I usually only compile, I do not run install, so I have tried both with gisbase="/home/veroandreo/software/grass79-dev/dist.x86_64-pc-linux-gnu" where the etc/ folder lives and also with the output of  `grass80dev --config path` which is `/home/veroandreo/software/grass79-dev/bin.x86_64-pc-linux-gnu/grass` (grass80dev is a symbolic link only), but in both cases I get: 

```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-22-8b9cf3c83c02> in <module>
     11 # Import the GRASS GIS packages we need.
     12 import grass.script as gs
---> 13 import grass.jupyter as gj
     14 
     15 

ModuleNotFoundError: No module named 'grass.jupyter'
```

Do you know what else should I try/set up to run the notebooks from the local copy of the repo in case binder keeps failing on this end?

**Comment by veroandreo** [comment]
Here the Binder error in my 4th attempt today: 

![image](https://user-images.githubusercontent.com/20075188/133941786-4a842b05-9850-45eb-ab8f-b672b3310595.png)

**Comment by petrasovaa** [comment]
Sorry, we seem to have issues with the server from where some of the data are being downloaded.

**Comment by veroandreo** [comment]
Binder link works now, looks really beautiful! :star_struck:
